# Generated by Django 5.2.7 on 2025-10-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customusermodel",
            name="company_name",
        ),
    ]
