# Generated by Django 5.2.7 on 2025-10-08 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applicant", "0001_initial"),
        ("recruiter", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="recruiter.jobpost",
            ),
        ),
        migrations.AddField(
            model_name="savedjob",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_by",
                to="recruiter.jobpost",
            ),
        ),
        migrations.AddField(
            model_name="savedjob",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
